-- Production: no demo seed data.
-- Configure public marketing copy via Admin → Website content (site_content keys).
-- Promote your account after signup:
--   UPDATE public.profiles SET role = 'super_admin' WHERE email = 'your@email.com';
